# Generated by Django 6.0.4 on 2026-04-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_hashtag_posthashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='posts', through='posts.PostHashtag', to='posts.hashtag'),
        ),
    ]
