# Generated by Django 6.0.4 on 2026-05-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_count',
        ),
    ]
