# Generated by Django 6.0.4 on 2026-05-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
    ]
