# Generated by Django 6.0.4 on 2026-05-19 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_savepost'),
        ('posts', '0007_remove_post_likes_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('id')), _negated=True), name='prevent_self_parent_comment'),
        ),
    ]
